debug: false
use-permissions: true
messages:
  no-permission: "Sorry, you don't have permission to create an Autocrafter of that type."
world-selection: whitelist
world-list:
  - world
  - world_the_end
  - world_nether

recipe-selection: blacklist
recipe-list: []